FROM node:19-alpine   
COPY my-react-app/package.json /app/my-react-app/  
COPY my-react-app/public/* /app/my-react-app/public/
COPY my-react-app/src/* /app/my-react-app/src/
WORKDIR /app/my-react-app 
RUN npm install
RUN npm run build 
COPY package.json /app/
COPY server.js /app/
WORKDIR /app            
RUN npm install    
CMD [ "npm", "start" ] 