version: '3.3' # Or remove this line for version 1

services:  # Make sure this line is not indented
  backend:  # One level of indentation
    image: rushenhansana/testing:backend_1.0
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: db
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/game_user
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: ThePassword

  db:   # One level of indentation (same as 'backend')
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: game_user
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_ROOT_PASSWORD: root_password
